# Generated by Django 2.1 on 2020-12-23 17:59

import content.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'content_categories',
            },
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alpha-numeric characters are allowed.')])),
                ('body', models.CharField(default=None, max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alpha-numeric characters are allowed.')])),
                ('summary', models.CharField(default=None, max_length=60, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alpha-numeric characters are allowed.')])),
                ('document', models.FileField(upload_to=content.models.content_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'contents',
            },
        ),
        migrations.AddField(
            model_name='contentcategories',
            name='content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='content_category', to='content.Contents'),
        ),
    ]
