# Generated by Django 2.1 on 2020-12-25 09:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcategories',
            name='content',
        ),
        migrations.AddField(
            model_name='contents',
            name='categories',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='contents',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='content_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contents',
            name='body',
            field=models.CharField(default=None, max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]*$', 'Only alpha-numeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='contents',
            name='summary',
            field=models.CharField(default=None, max_length=60, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]*$', 'Only alpha-numeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='contents',
            name='title',
            field=models.CharField(default=None, max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]*$', 'Only alpha-numeric characters are allowed.')]),
        ),
        migrations.DeleteModel(
            name='ContentCategories',
        ),
    ]
