# Generated by Django 2.1 on 2020-12-25 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201225_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='content_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
